<?php

namespace AppBundle\Entity\Movie;

use Doctrine\ORM\EntityRepository;

/**
 * MovieReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieReviewRepository extends EntityRepository
{
    /**
     * @param int $id
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function countMovieReviewByMovie($id)
    {
        $qb = $this->createQueryBuilder('r');
        $qb->select('COUNT(r)')
            ->join('r.movie', 'm')
            ->where('m.id = :id')
            ->setParameter('id', $id)
        ;

        return $qb;
    }

    public function getAvgReviews($id)
    {
        $qb = $this->createQueryBuilder('r');
        $qb->select('AVG(r.review)')
           ->join('r.movie', 'm')
           ->where('m.id = :id')
           ->setParameter('id', $id)
        ;

        return $qb;
    }
}
