bazinga_faker:
    orm: doctrine
    entities:
        AppBundle\Entity\Movie\Movie:
            number: 100
            custom_formatters:
                director:   { method: name }
                title:      { method: word }